CREATE TABLE [dbo].[Order]
(
	[id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()),
	[name] VARCHAR(50) NOT NULL,
	[userId] UNIQUEIDENTIFIER NOT NULL,
	[description] VARCHAR(MAX) NOT NULL,
	CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED ([id] ASC),
	CONSTRAINT [FK_User_Order] FOREIGN KEY ([userId]) REFERENCES [User] (id),
)
