CREATE TABLE [dbo].[User]
(
	[id] UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWSEQUENTIALID()),
	[name] VARCHAR(50) NOT NULL,
	[email] VARCHAR(150) NOT NULL,
	[password] VARCHAR(20) NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([id] ASC)
)
